### ISSUE TITLE
Static files are not included in build

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#102]
**Describe the bug**
When building a package out of MATRX, the static files in MATRX Visualizer are not included.

**To Reproduce**
Follow the build procedure.

**Expected behavior**
No static files included in a build.

**Screenshots**
N/A

**Stacktrace**
N/A

**Additional context**
@mlstolk we discussed a solution about this. Did this seemed work? If so please comment on what you did to solve it (preferably referring to a commit where you did so), and close this issue.

**Comment by mlstolk** [comment]
I did solve it in branch #82. I will file a merge request, so it can be tested by others.
After the test + merge, this issue can be closed.
