### ISSUE TITLE
Include task?

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#106]
**What is your question?**
Can we include Tjalling's thesis use case into the task lib of MATRX?

**To what is your question related?**
- [ ] I am not sure if I should use MATRX.
- [ ] I have a question about the idea behind MATRX.
- [ ] I don't know how to do something with MATRX.
- [ ] I don't know where to find something.
- [ ] I think I found a bug, but I am not sure.
- [ ] I want to contribute, but don't know where to start.
- [x] Something else.

**Comment by thaije** [comment]
Yes, but is has no functionality at all. It is only a picture with a static non-moving agent. Any behaviour (tank shoots drone, radar detects drone, etc.) needs to be programmed.
