### ISSUE TITLE
Send message as action

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#113]
**Is your feature request related to a problem? Please describe.**
Sending a message is now for 'free', in the sense that it does not cost an actual action and as an extension time. However, there have been request for a message sending action, furthermore users initially seem to assume that sending a message is an action and start looking for that functionality there.

**Describe the solution you would like**
Add a new extension of `Action` called `SendMessageAction` that receives a `Message` instance and sends it to the right agents through the `GridWorld` instance. This requires the `GridWorld` to have a function that takes this message and appends it to a list of messages that need to be send that step. The appropriate `is_possible` method should check for things such as; is it a `Message` object? Does the receiver (and sender) exist? Is the message not already send? And potentially more.

This may also allow for more complex messageing properties, such as a range or the chance of intercepting or tampering with messages.

**Describe alternatives you have considered**
An alternative is to keep the message system as it is now but document it more clearer and potentially implement a blocking functionality into `GridWorld` that pauses agents who just send a message (this to mimick the time cost of sending messages). However, this sounds a bit more hacky.

**Additional context**
Important to note here is that this feature would allow _two_ ways of sending messages. Both can be used interchangeably within one task, and even world step. This can add more complexity to the messaging system. We should wonder, if we will implement this, if the old system still has merit.

Also, by making it an action it allows for simpler integration with loggers (as we can log actions, but not communication as of yet). 

Finally, if one chooses to send a message with an action; are multiple messages within one action possible?

**Comment by thaije** [comment]
After 1.5 years of usage, the priority of this feature request has been very low. There have been no instances of (new) users bringing up this point. They have however brought up the point of a lack of documentation, which cannot be completely solved with intuitive code.. 

So this issue will be closed, and instead explicitly described in the MATRX tutorial: #284
