### ISSUE TITLE
Exception in message manager

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#117]
**Describe the bug**
At the `MessageManager` there is this code segment with a way to broad exception:
```python
try:
    # check if it is a list encoded as a string (sent via api)
    to_ids = eval(mssg.to_id)

    # create a new message addressed to this list of IDs, and reprocess
    new_message = Message(content=mssg.content, from_id=mssg.from_id, to_id=to_ids)
    self._decode_message_receiver(new_message, all_agent_ids, teams, tick)
except:
    pass
```

**To Reproduce**
N/A

**Expected behavior**
Either a clear and informative exception is raised, or use appropriate if-statements to check if things should be working.

**Screenshots**
N/A

**Stacktrace**
N/A

**Additional context**
N/A

**Comment by thaije** [comment]
See issue #146
