### ISSUE TITLE
Generic exception try-catch api

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#118]
**Describe the bug**
The API file, api.py, has several generic try-catch. Either use appropriate if-else statements to check if things should work, or make more informative exception catches and appropriate messages.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Stacktrace**
N/A

**Additional context**
N/A

**Comment by thaije** [comment]
Where possible this has been fixed, see commit https://github.com/matrx-software/matrx/commit/5d876d7cf63123d4df31ee8223614675527bbed7. 

There do remain some try catch loops, which cannot be done (as far as I know) in another way without sacrificing robustness.

**Comment by thaije** [comment]
See issue #146
