### ISSUE TITLE
PyPi MATRX 1.0.0 package misses MATRX-visualizer files

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#122]
**Describe the bug**
The MATRX visualizer is broken in the MATRX 1.0.0 PyPi distribution. 
This is caused by the matrx-visualizer folder which is incomplete. It only contains the `visualization_server.py` and `__init__.py` files. The `static` and `templates` folders are missing. To check this see the PyPi distribtuion https://pypi.org/project/matrx/#files and open the `matrx-1.0.0.tar.gz` file > go to matrx-visualizer folder. It should match with https://github.com/matrx-software/matrx/tree/dev/matrx_visualizer. 

**To Reproduce**
Install MATRX using pip: `pip install matrx`
Copy paste the main.py from git: https://github.com/matrx-software/matrx/blob/dev/main.py 
Run MATRX: `python main.py`
Point your internet browser to the MATRX visualizer: `localhost:3000`. 
In the terminal this gives me the error: 
```
[2020-03-25 17:47:11,142] ERROR in app: Exception on / [GET]
...... stacktrace ....
jinja2.exceptions.TemplateNotFound: start.html
```
In the browser I get a 500 - Internal Server Error. 

**Expected behavior**
The matrx-visualizer folder being complete and the GUI working. 

**Screenshots**
-
**Stacktrace**
-

**Additional context**
We encountered this bug before, but I don't know who or how it was fixed. @jwaa @mlstolk?

**Comment by thaije** [comment]
If I look into the MATRX-visualizer package installed on my computer (did fresh install) at `/home/tjalling/.local/lib/python3.6/site-packages/matrx_visualizer` , it does show that the static folder is installed and thus only the templates folder is missing. Nonetheless, the templates folder is missing from the PyPi package.

**Comment by jwaa** [comment]
On it!

**Comment by jwaa** [comment]
Being worked on in branch 'hotfix-1.0.1'

**Comment by jwaa** [comment]
Adding a `MANIFEST.in` file seemed to have worked. See [this documentation](https://docs.python.org/2/distutils/sourcedist.html#manifest-template)

We are calling both the command to build a binary _and_ source distribution. The `package_data` keyword for setuputils (in `setup.py`) only works with binary distributions. See this [Stack](https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute).

**Comment by jwaa** [comment]
Other troubles; my laptop does not seems to allow me uploading to test-PyPi from the VPN connection or my home network. Will try and upload it from another computer.

**Comment by jwaa** [comment]
It seems something else is going on. I can't upload packages to neither the test servers nor the actual ones. I get a "504: Gateway Time-out" response from the actual servers.

@thaije Can you see if you can run `python setup,py test` from the 'hotfix-1.0.1' branch?
