### ISSUE TITLE
Repository as part of a Github Team

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#123]
**Is your feature request related to a problem? Please describe.**
Currently we only have one Owner (the matrx-software account) and everyone else is a Collaborator. With a Team we can assign more owners, admins, maintainers, etc.

**Describe the solution you would like**
Assign this repository under a new team for MATRX.

**Describe alternatives you have considered**
Just keep doing what we are doing now and when needed logging into the MATRX account.

**Additional context**
N/A

**Comment by jwaa** [comment]
Two options:
- Make a new organisation/team, but this requires a new name (matrx and matrx-software are taken...)
- Change the matrx-software account into an organisation/team. But this are the consequences:
```
Account transformation warning
What you are about to do is an irreversible and destructive process. Please be aware:

    Any private repositories owned by matrx-software will be disabled
    You will no longer be able to sign in to matrx-software (all administrative privileges will be bestowed upon the owners you choose)
    Any user-specific information (OAuth tokens, SSH keys, Job Profile, etc) will be erased
    Any commits credited to matrx-software will no longer be linked to this GitHub account
    The total amount of collaborators across private repositories will be the total amount of seats for the organization

If you are using matrx-software as a personal account, you should create a new personal account before transforming matrx-software into an organization.
```

@thaije Opinions?

**Comment by thaije** [comment]
@jwaa I would suggest the second option, it's better to have 1 account/ organisation/team set up properly for our needs, than having all kinds of extra teams and accounts, which makes it more confusing. Also, the transformation warning does not seem that bad, we don't have any private repositories and can assign ourselves as admin. 

The only point I don't fully understand is the last one: 
`The total amount of collaborators across private repositories will be the total amount of seats for the organization`. 

Does this mean we have zero seats for the organization, as we don't have any private repositories?

**Comment by jwaa** [comment]
Hmm.. good point. With a quick search I found [this](https://help.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/upgrading-your-github-subscription#adding-seats-to-your-organization). It seems to imply that Seats are just users linked to the organisation who all have access to the organisation's private repositories.

**Comment by jwaa** [comment]
According to [this](https://github.com/organizations/plan), it seems that Seats are just paid thing as we wont have access to private repos with a free organization.
