### ISSUE TITLE
API overflows console output

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#127]
**Describe the bug**
The console is overflowing with the following message if GridWorld creation takes long:
```
api request not valid: {'error_code': 400, 'error_message': "MATRX hasn't started yet."}
Throwing error 400 Bad Request: MATRX hasn't started yet.
```
This happens because world creation is relatively slow for those with increasingly more objects (see #126)

**To Reproduce**
Create a huge world, add tiles and objects to every location.

**Expected behavior**
Less spam in the console, especially because it hides the progress of world creation now.

**Screenshots**
N/A

**Stacktrace**
N/A

**Additional context**
Might be difficult to fix... Since the API is outputting this statement and has no clear way of knowing whether a world is in creation or just blew up due to an exception of some sorts.

**Comment by thaije** [comment]
See commit https://github.com/matrx-software/matrx/commit/ef6a37c7e64eb2269e4d6ec625357f4b23533dfe 
API outputs now only when `verbose=True` is passed to the `WorldBuilder()`
