### ISSUE TITLE
Add markdown support for  the documentation

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#13]
<a href="https://github.com/matrxs"><img src="https://avatars1.githubusercontent.com/u/58174304?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [matrxs](https://github.com/matrxs)**
_Tuesday Jan 21, 2020 at 08:31 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/12_

----

Markdown is an easier and more intuitive method of writing Richt Text, compared to the RichStructuredText (.rst) format. Markdown is also often used for wiki's and readme's of code repositories. 

As such, it would ease the creation of new documentation pages a lot if markdown was supported.

**Comment by matrx-software** [comment]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thaije](https://github.com/thaije)**
_Friday Feb 07, 2020 at 07:15 GMT_

----

https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx

**Comment by thaije** [comment]
Readthedocs will only be used for the reference API documentation, not for tutorials. So this is not needed anymore.
