### ISSUE TITLE
Dropdown not right for agent view selection

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#131]
**Describe the bug**
At times when I refresh the start screen of MATRX, the drop down stops containing agents but simply has text in it (see screenshot).

**To Reproduce**
Start a world, and when it crashes (for me mostly due to the API and/or Message Manager crashing, see for example due to #121), refresh the main screen and click the drop down.

**Expected behavior**
To either contain an error message or the expected list of agents.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/6059315/78121443-b0ece980-740b-11ea-887a-fd47142b8fcf.png)

**Stacktrace**
N/A

**Additional context**
Applies to Firefox 74.0

**Comment by thaije** [comment]
If the API crashes, the dropdown can't be filled. Because of issue #121 the API did crash quite a lot, which made the situation above occur quite frequently. Issue #121 has now been fixed thus I expect this issue to not occur anymore. So closing for now.
