### ISSUE TITLE
StateTracker not working in PatrollingAgent

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#137]
**Describe the bug**
The creation of the `PatrollingAgent` with its `initialise()` method fails because it now requires the `SenseCapability` instance which is not given in that agent.

**To Reproduce**
Create a world with a patrolling agent and see it fail.

**Expected behavior**
That it does not fail.

To solve the `sense_capability` parameter from the `StateTracker`. So: remove it from [this line](https://github.com/matrx-software/matrx/blob/dev/matrx/agents/agent_utils/state_tracker.py#L10) and remove [this line](https://github.com/matrx-software/matrx/blob/dev/matrx/agents/agent_utils/state_tracker.py#L21). Nothing else is needed, since sense capability is actually obtained from the perceived state and this attribute is never used (just forgot to remove it).

**Screenshots**
N/A

**Stacktrace**
```python
self.initialize(api_info)
  File "C:\Users\zoelenev\PycharmProjects\Co-Learing_Scenario\venv\lib\site-packages\matrx\grid_world.py", line 60, in initialize
    agent_body.brain_initialize_func()
  File "C:\Users\zoelenev\PycharmProjects\Co-Learing_Scenario\venv\lib\site-packages\matrx\agents\agent_types\patrolling_agent.py", line 17, in initialize
    self.state_tracker = StateTracker(agent_id=self.agent_id)
TypeError: __init__() missing 1 required positional argument: 'sense_capability'
```

**Additional context**
This is related to the change of FOV occlusion.

**Comment by thaije** [comment]
Removed the sense_capability that was being required by the StateTracker. This is now fetched from the state as seen [here](https://github.com/matrx-software/matrx/blob/dev/matrx/agents/agent_utils/state_tracker.py#L61) during the StateTracker.update() function. 

Apparently, the `state_tracker.get_traversability_map` function now returns a tuple: the traversability map with 1-s and 0-s indicating traversability, and an obj_grid with the IDs of the objects. The navigator only was expecting the first traversability_map, which gave an additional error. To fix this I changed this line in the Navigator: 
```self.__occupation_map = state_tracker.get_traversability_map(inverted=True)```

To this: 
````self.__occupation_map, obj_grid = state_tracker.get_traversability_map(inverted=True)```

Subsequently ignoring the obj_grid var in the Navigator. 

@jwaa let me know if you had plans for using the obj_grid / FOV functionality for the Navigator, as it is now ignored.
