### ISSUE TITLE
Adjust EnvObject properties fails

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#138]
**Describe the bug**
The `EnvObject` treats the adjustable properties list still as a dict while it is a list.

**To Reproduce**
N/A

**Expected behavior**
Not crashing when adjusting a property.

To fix this change [this line](https://github.com/matrx-software/matrx/blob/dev/matrx/objects/env_object.py#L160):
```python
if property_name in self.customizable_properties.keys():
```
Into this line:
```python
if property_name in customizable_properties:
```
I think that should solve it...

**Screenshots**
N/A

**Stacktrace**

**Additional context**
N/A

**Comment by thaije** [comment]
Fixed as stated in the description.
