### ISSUE TITLE
Seperate thread for writing log files

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#14]
<a href="https://github.com/matrxs"><img src="https://avatars1.githubusercontent.com/u/58174304?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [matrxs](https://github.com/matrxs)**
_Tuesday Jan 21, 2020 at 10:04 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/13_

----

Right now, when running many MATRXS worlds concurrently for applications which require many simulations, a slowdown seems to be the sequential writing of log outputs to disk. This is especially true for TNO laptops, for which the harddrive is encrypted and i/o executions are quite slow. 
To solve this, writing log files might be performed in a separate thread which is killed / joins the maintrhead when done.

**Comment by thaije** [comment]
Merged with #160.
