### ISSUE TITLE
Split get_env_object function

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#16]
<a href="https://github.com/matrxs"><img src="https://avatars1.githubusercontent.com/u/58174304?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [matrxs](https://github.com/matrxs)**
_Tuesday Jan 21, 2020 at 13:20 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/15_

----

get_env_object now accepts ID, type and name. 
Split this function into: 
- `get_env_object(agent_id)`. Which returns 1 object (with that ID) or False 
- `filter_env_objects(obj_type=False, obj_name=False)`. Which returns a list of objects which meet the specified criteria. No criteria returns all env objects.

**Comment by sahil1610** [comment]
@matrx-software I would like to contribute

**Comment by jwaa** [comment]
Sure @sahil1610! I can set you up tomorrow. Do read our [contribution guide](https://matrx-software.com/how-to-contribute-to-matrx/) beforehand :)

If you need help, just ask.

**Comment by matrx-software** [comment]
@sahil1610, I gave you access. Welcome!

Please follow the aforementioned contribution guide if you wish to contribute. Start with a feature branch.

**Comment by thaije** [comment]
We now have a handy state object with built-in helper methods for filtering and finding objects and agents. It is available in agents, actions, loggers, object (update function). See among others #202.
