### ISSUE TITLE
Filter_state_objects in agent_brain

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#17]
<a href="https://github.com/matrxs"><img src="https://avatars1.githubusercontent.com/u/58174304?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [matrxs](https://github.com/matrxs)**
_Tuesday Jan 21, 2020 at 13:21 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/16_

----

The same function as the get_env_object and filter_env_objects, as specified in issue #15. Only difference is this function can do the same filtering for a state in an agent_brain, as from there the grid_world.get_env_object function cannot be accessed.

**Comment by thaije** [comment]
Now implemented in the form of the state object that includes helper functions. See https://github.com/matrx-software/matrx/blob/master/matrx/cases/bw4t/bw4t_agents.py for example usage.
