### ISSUE TITLE
Interface start screen not available from non-MATRX hosting website

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#175]
**Describe the bug**
If you host MATRX on a laptop with a local network, only the hosting laptop can access the agent overview page (localhost:3000). Connecting with another laptop to that network and trying to access that page throws an error in the console.

**To Reproduce**
Do the steps above. 

**Expected behavior**
God agent is also available from other non-MATRX hosting laptops. 

**Additional context**
Other agents are accessible, only the localhost:3000 page is not available. Most likely the cause is in the dashboard.js file where the url is hardcoded to localhost.

**Comment by jwaa** [comment]
@thaije Now more and more projects will be doing experiments with MATRX, including a "Wizard" who needs to start/pause/stop the task, would it make sense to fix this bug in the next milestone (or even in an upcoming hotfix)? I have no idea how much effort this would be. Perhaps the option of providing an IP adress to the default visualization through the world builder (that defaults to "localhost")? No idea how we get that in the dashboard.js though.

**Comment by thaije** [comment]
@jwaa The fix itself is trivial. I added it to the next release :)
