### ISSUE TITLE
MATRX-version in default visualisation 

### ISSUE THREAD

**Issue by TjeerdS** [matrx-software/matrx#176]
_It would be nice to have the version of MATRX in the default visualisation, because this always makes it clear with what version you are currently working, and you would not have to search for it in the code._

**Comment by jwaa** [comment]
@thaije Would this be doable? The version number is known in the __version__.py, but we need to get it to the front-end as well. I am quite hesitant to just add it to states, that would just clutter states further. But it seems quite an effort to create a unique API call just to get the version. Is there some "initialization" API call when the visualization starts? If so, we can add it there.
