### ISSUE TITLE
Potential bug; Flask v1.1.2 fails with MATRX visualization

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#179]
**Describe the bug**
See [this report](https://ci.tno.nl/gitlab/aims-experimentatie2/matrxs/-/issues/93) at the AIMS project. It describes a connection failure between the JS server-client and their custom visualization Flask server.

**To Reproduce**
Should be test if this same bug applies to the MATRX Visualizer.

**Expected behavior**
Correctly loading of the pages, due to a succesful connection between the visualization server and the JS server-client.

**Screenshots**
If it fails you see this on localhost:3000
![afbeelding](https://user-images.githubusercontent.com/6059315/84744271-4d5a6d00-afb3-11ea-91ff-f390bb4f2115.png)

**Stacktrace**
A stacktrace can be viewed in your browser's console.

**Additional context**
The issue might be due to a combination of how MATRX uses Flask and the Flask v1.1.2 patch. However, this seems unlikely as the `visualization_server.py` is a very simple Flask server. Furthermore, the Flask issue list does not show an apparent report of such an issue, this combined with the relative few patch release of Flask (about once or twice a year), it is unlikely that this issue will be fixed soon. 

A simple solution for us would be to fix the dependency of Flask to v1.1.1 and ignore [these bug fixes](https://flask.palletsprojects.com/en/1.1.x/changelog/#version-1-1-2). But only if MATRX suffers the same bug, if not it is a bug in the custom visualization of AIMS.

**Comment by thaije** [comment]
Flask can be finicky with file paths, and the Flask 1.1.2 patch seems to have changed something in the pointing to the static folder with static web files of our visualization web server. [In AIMS this was solved](https://ci.tno.nl/gitlab/aims-experimentatie2/matrxs/-/issues/93) by changing how the paths were defined, something which was already done in the newer versions of MATRX. 

However, it is worth it to investigate if using the[ `url_for()` function](https://flask.palletsprojects.com/en/1.1.x/quickstart/) can solve the issues with file paths forever, as [used](https://github.com/realpython/flask-by-example/blob/master/templates/index.html#L8) here. 

Thus, there should be no problems with MATRX and Flask 1.1.2 itself. If someone still has this problem, please report it in this issue and I'll take another look.

**Comment by jwaa** [comment]
In response to this bug in AIMS the Flask dependency for MATRX is now fixed to v1.1.1, I will set this back to =>v1.1.1 in a hotfix today.
