### ISSUE TITLE
New State object fails unpredictably when treated as dict

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#195]
**Describe the bug**
The new state object is a custom dict object. However, checking if a key is present in the usual way always returns True: 
```
if "Key_21" in state.keys():
    ....
``` 
This always returns True. 

**To Reproduce**
Try the above in e.g. the `filter_observations` function of the `AgentBrain.py`. 

**Expected behavior**
Either work as a normal dict, or throw an error / exception. 

**Additional context**
This was the root of a very weird bug encountered during the upgrading of the Coactive teaming blanket search task to MATRX v1.1.0. They implemented their own memory, which removed objects not longer present in the state. However, they checked for object presence as described above, which always returned True. So there were never any objects removed from the agents their memories.

**Comment by thaije** [comment]
Might also be enough to put this in a lot of tutorials in big **NOTE** boxes.

**Comment by jwaa** [comment]
This is unexpected. At the moment I am a bit clueless why this happens. I will try to dive in this somewhere today to see if I can find the reason for this. 

Putting this in Notes, is not really an option. The entire idea was that State could be used as a dict as well. So I will see if I can find the root issue here.
