### ISSUE TITLE
Add deploy steps to contribution guide

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#197]
**Is your feature request related to a problem? Please describe.**
It is quite cumbersome to deploy a new MATRX version. It would be nice if everything you need would be in one spot.

**Describe the solution you would like**
An additional section in the contribution guide that describes step by step how to deploy a new MATRX version:
1) Merge with master
2) Upload it to test pypi
3) Test it (e.g. vis_test, bw4t etc)
4) If everything works, tag the version
5) Create release notes
6) Upload to pypi

**Describe alternatives you have considered**
Instead of doing it manually we can use CI, but no idea how that works.

**Additional context**
N/A

**Comment by thaije** [comment]
In addition, adding the actual git commands would be nice for step 4: 
`git pull ` (latest master branch you pushed)
`git tag v_YOUR_VERSION -a`
`git push --tags`

How to install from test server: 
See version on test pypi: https://test.pypi.org/project/matrx/1.1.0a1/

**Comment by jwaa** [comment]
[Done!](https://matrx-software.com/how-to-contribute-to-matrx/)
