### ISSUE TITLE
Document the state properties

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#198]
**Is your feature request related to a problem? Please describe.**
It is often unclear which state properties each object has.

**Describe the solution you would like**
A bit of documentation on the properties each object has in the states. Preferably on the website, though it would be nice if it is also documented in the code itself.

**Describe alternatives you have considered**
N/A

**Additional context**
N/A

**Comment by thaije** [comment]
@jwaa the current properties of objects and agents have all been documented to my knowledge at the time of writing. A general description of the state is scheduled to be included in the tutorial
