### ISSUE TITLE
subtile objects block eachothers Context menu

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#200]
**Describe the bug**
The subtile functionality makes it possible to have multiple objects in 1 tile in the MATRX visualizer. However, doing so, the top most object blocks clicks for the objects below it when opening the context menu with right click. The same is true for objects that are in the same tile as a (selected) agent. Opening context menu's there is also problematic. 

**To Reproduce**
Stack a number of objects in the same tile, but different subtiles, and  try to open (in human agent view) a context menu on each of the objects. 

**Expected behavior**
Context menu's can be opened by clicking on visible objects, and should not be blocked by invisible divs in the visualization frontend. 

**Additional context**
The subtile functionality might be something that could lead to a lot of comptability and visualization difficulties now and in the future. I don't see it's advantage over creating a regular room and placing objects each in their own tile.

**Comment by thaije** [comment]
@jwaa misschien toch maar die subtile functionaliteit er standaard uithalen. Ik zie wel een boel issues zoals deze aankomen als mensen het meer gaan gebruiken. Het heeft ook geen echt voordel boven gewoon meer tiles nemen toch?

**Comment by thaije** [comment]
Also check why the context menu doesn't open on the bg tiles

**Comment by thaije** [comment]
Fixed in AIMS, see: https://ci.tno.nl/gitlab/coactive_teaming/capability_pattern/-/commit/42d3bcccbaabbf24322f405743efdd202321218e

**Comment by jwaa** [comment]
Can the fixed easily be ported? If so, I would rather not remove a feature we just added. 

However, if you foresee many issues in the future I trust your judgement. In that case let's remove it in the next hotfix. So I leave it up to you @thaije :)

**Comment by thaije** [comment]
@jwaa yes the fix fortunatly was quite easy and can be easily ported. However, I am more concerned for this feature that people will use the subtiles as a hack/shortcut to create rooms with objects, instead of having them make a real room. However, I can't come up with any difficulties with doing so for the user at the moment, so maybe it isn't that bad..

**Comment by jwaa** [comment]
Time is precious, so lets leave it in until it gives issues :)
