### ISSUE TITLE
Use the Custom State object in all of MATRX

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#202]
**Is your feature request related to a problem? Please describe.**
The new state object is very handy with searching for objects based on their name, instead of the unpredictable (unique) IDs. However, the other parts of MATRX still use the old dictionary state. It would be very useful to deploy the usage of the new state everywhere. 

This would make it much easier to search and filter for objects in actions and loggers. It is especially apparent now when it is easy in the agent, and more troublesome (need to have a object ID, which you need to loop through all of the environment objects for) in actions and loggers. 

**Describe the solution you would like**
Usage of the custom State object throughout all code of MATRX, for loggers, actions, agents, etc. 

**Describe alternatives you have considered**
-

**Additional Context**
As of now, this issue was circumvented by removing the random number appended to the ID of objects in some projects. Such that the ID is the same as the name, and it can be easily fetched from the state. However, changing the MATRX core code is not desired, and also much more difficult now that MATRX is a Python package.

**Comment by thaije** [comment]
@jwaa I don't know if you already had an issue for this one? I couldn't find it atleast.

**Comment by jwaa** [comment]
@thaije No we hadn't. So good that you created one! I see you already planned it for v1.2.0, so I will replace the request with the feature label.

**Comment by thaije** [comment]
@jwaa in the mean time, do we have any handy way to fetch an object using it's name, aside from looping through all of the gridworld objects in an action / logger?

**Comment by jwaa** [comment]
@thaije What you could try is use the State for that: Just create a new State object based on the dict you receive and use the State functionality to find an object by name (e.g. `state[{'name': 'some_name'}]`). Though this may cause some circular import issues... 

Another option would be to copy some code from the State object that does this for you, though this would require some tweaking. The gain is that you still loop through everything, but highly efficiently (though not that readable anymore as a for-loop or list-comprehension). 

P.s. If you worry about efficiency, as a rule-of-thumb (from slow to fast): for-loop > list-comprehension => map() method

**Comment by jwaa** [comment]
@thaije Is it wise to include this in v2.1? It is quite a big issue with the potential to break a lot (e.g. world goals, loggers, etc.). Do we dare to take this one one in the coming two weeks?

**Comment by thaije** [comment]
@jwaa I think this feature would be a major upgrade for MATRX, and also make it more consistent in how you (can) use the state everywhere. With regards to breaking worlds etc, is that really the case? Isn't the new state backwards compatible, in that you can directly search for an object like the previous state dict, and can also loop through it 1 object at a time?

**Comment by jwaa** [comment]
well in theory it shouldn't break that much yes. Though State only mimics a dict, it's not even fully ducktyped. So it depends on what people do with the dict and if it is supported by State as well. I will try and take a look at it. Mostly have to find the time to do within these two weeks :)

**Comment by jwaa** [comment]
@thaije Just completed the use of `State` in the API (up to the point it is jsonified). Do we also want `State` to be used in all places where `GridWorld` is now used?

I think these are all places where `GridWorld` is actually passed;
- [ ] All actions `is_possible` methods.
- [ ] All world goals, both `goal_reached` and `get_progress` methods.
- [ ] All loggers in the `log` method (through `_grid_world_log` which also uses it at `_needs_to_log` method).

Where we can't replace `GridWorld` with a `State`:
- All actions `mutate` methods.
- All `update` methods in every `EnvObject`.
As these actually change the `GridWorld`.

Besides using the `State` in the API and at the places in the first list, anywhere else we want to use `State`?

**Comment by thaije** [comment]
@jwaa Nice work. I think the loggers, and actions are the most desired places for its use, but for consistency I would just make the state everywhere where it is used available in the new format if that is possible? Is that much work?

Also, why exactly is it not possible in the `mutate` of action methods to use the new `State`? It is not because the new `State` is a read-only copy of some sort right? Because that was the whole issue with the state that was edited by agents in their `decide_on_action`, that any changes made there also changed the real gridworld state.

**Comment by jwaa** [comment]
Loggers can be done fairly easily but is likely to break previous versions. As it is quite a leap from grid world to state. The Logger never used a dict, just the world directly.

Regarding the mutate; the link only goes for the objects already in State. Adding or removing objects will not carry over to the world as that does not use a State but a 2d grid. Also you will have to add a lot more funtionality to State that is currently in GridWorld to build a wide variety of helper methods to add, remove and change properties. Currently the State only helps in finding and reading properties.

So to support `mutate`, `update` or any other method that changes the world is a major overhaul. It also introduces complexity afterwards; suddenly you change the world by just observing it, if you add, remove or change an object there.

**Comment by thaije** [comment]
Okay that does sound difficult. A concession would be to make the new state available in the `mutate` and `update` functions so they can be used to easily find objects and their IDs based on their proerties etc which is a big help, but changing, removing or adding an object via the `State` throws an error and notes that the gridworld should be altered directly and not via `state`?

**Comment by jwaa** [comment]
Was thinking about that as well. It would change the signatures of those methods though, breaking any custom classes of them (both actions and custom objects with an uodatr) :(

Not really sure if raising an exception will work. How do you know the difference within State that some property change or object removal is part of a filter observation or an action call? As these are common in both.

If we get State to be read-only, does it matter much if you change it in a mutate?

**Comment by jwaa** [comment]
We may have a way out for the signature change... As both the `mutate` and `is_possible` make use of a `**kwargs` to catch any custom parameters. We can just stick the `State` in there by default, which causes every custom implementation to just contain it in its kwargs.

I will just do that!

**Comment by jwaa** [comment]
Done for `Action` and all it children. However, the default MATRX actions just receive the `State` they do not use it. Meaning that they still use the helper methods in `GridWorld` to find their objects.

Sadly I cannot do something similar for `Logger` without changing its signature or replacing `GridWorld` with `State`. As both will break any custom `Logger` out there.

**Comment by thaije** [comment]
So integration of the new state is now as follows:
- API gets the new state and uses it 
- Actions get the new state but don't use it yet 
- Logger's don't get the new State because custom loggers would break as they can't deal with the new param
- Goals also don't get the new State because it would also break custom loggers

**Comment by jwaa** [comment]
Created alternative logger and goal classes with postfix "V2" to represent those that receive also the world state as a `State` object. In addition set a deprecation warning to the regular versions of these classes to switch to these "V2" versions. 

In a future release the old versions can be removed, and the "V2" versions set to deprecated. With new regularly named classes of these (e.g., `GridWorldLoggerV2` -> `GridWorldLogger`) that are simply copies of the "V2" versions. In another next release we can then remove the "V2" versions again to have a transition to the new loggers and world goals that use state without harming backwards compatibility without warning.
