### ISSUE TITLE
World builder functions add_agent and add_human_agent use a different argument name

### ISSUE THREAD

**Issue by jewol** [matrx-software/matrx#206]
In _world_builder.py_ there are (among others) two functions named _add_agent_ and _add_human_agent_. To initialize an agent you provide a brain with the argument name _agent_brain_ (for method add_agent) and _agent_ (for method add_human_agent). The latter argument should also be named _agent_brain_ to stay consistent across the code-base.

**Comment by jwaa** [comment]
This is a common issue in the `WorldBuilder`; the consistency between the methods is a bit lacking. A more intrusive example is that at times the `name` property is mandatory and at other times it is not.

I will create an encapsulating issue for this where we can collect these (usability) bugs.

**Comment by thaije** [comment]
Inconsistencies fixed: 
- `agent` param in `add_agent` and `add_agent_prospect` renamed to `agent_brain` to be consistent with `add_human_agent`
- `name` param is required for consistency in all functions where it is a parameter, as in the majority of the functions there is no check on duplicate names (e.g. name for rooms, areas, etc.) and in the majority it is an issue if MATRX by default assigns duplicate names (e.g. multiple rooms with identical names where state.get_room_doors returns multiple doors).
- Added the visualize properties to all functions: `visualize_size, visualize_shape, visualize_colour, visualize_depth, visualize_opacity`

The `add_room` function is also inconsistent and requires change, but what the best solution is I'm not sure.  Some but not all of the Door/Wall/Area object properties are listed as a parameter for the `add_room` function, some of the generic object properties (e.g. `visualize_depth`, but not `visualize_size`), and finally the custom_door_properties. We can either put all possible properties in the function specification (will be 20 properties or so), or simplify it. I chose for now the latter option, but this means it could break people's code:
```
def add_room(top_left_location, width, height, name,
                 door_locations=None, with_area_tiles=False, 
                 door_properties={},
                 wall_properties={},
                 area_properties={}):
```
The door, wall, and area properties dicts contain Door/Wall/Area properties, generic properties (visualize_depth, etc.), and custom properties. 
@jwaa  what do you think is the best solution for the `add_room` function?
