### ISSUE TITLE
Readthedocs documentation fails

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#209]
**Describe the bug**
It seems that not all documentation is included on ReadTheDocs. For example, the [WorldBuilder](https://github.com/matrx-software/matrx/blob/master/matrx/world_builder.py) is fully documented but this is not shown in the [master](http://docs.matrx-software.com/en/master/sections/_generated_autodoc/matrx.world_builder.WorldBuilder.html#matrx.world_builder.WorldBuilder)/[dev](http://docs.matrx-software.com/en/dev/sections/_generated_autodoc/matrx.world_builder.WorldBuilder.html)/[latest](http://docs.matrx-software.com/en/latest/sections/_generated_autodoc/matrx.world_builder.WorldBuilder.html) versions of the documentation.

**To Reproduce**
Go to the documentation page.

**Expected behavior**
The documentation we wrote with blood, sweat and tears is actually included on the web page.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/6059315/87043130-e8cab080-c1f4-11ea-9a6a-2c5159dcfdec.png)

**Stacktrace**
N/A

**Additional context**
Perhaps related to #166?

**Comment by thaije** [comment]
See https://github.com/matrx-software/matrx/pull/234
