### ISSUE TITLE
Central Point of Visualization

### ISSUE THREAD

**Issue by xDaya** [matrx-software/matrx#215]
**Is your feature request related to a problem? Please describe.**
Moving from MATRX 1.0 to 1.1, images connected to objects and agents now scale from the coordinates of the object in the center, in stead of the top left corner. Using a lot of large size objects, this messes with both my visualization and with the way I programmed these large objects.

**Describe the solution you would like**
For me it would be great if I could choose for center or left corner, to ensure that for my current scenario it still works but also that people can still go for the center option if that works better for them.

**Describe alternatives you have considered**
It is possible to change all images, but for me that would also mess up how I program large blocks.

**Comment by jwaa** [comment]
@xDaya Thanks for the request! For consistency, can you write your issue in the following format:

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example; "I'm always frustrated when [...]"

**Describe the solution you would like**
A clear and concise description of what you want to happen.

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by jwaa** [comment]
@thaije We already briefly discussed this. This setting xDaya talks about is part of the idea we had a few months ago for having "visualisation" settings (which buttons show, auto-play yes/no, etc.). You probably have a better overview of these kind of settings. Can you make a feature request for this? Then we can link this one to that issue.

**Comment by thaije** [comment]
@jwaa Yes indeed, at the time I thought we wouldn't need it. However with concrete requests such as this it might be good to add them on a case-by-case basis? Especially for backwards compatibility for some issues. I'll make an issue

**Comment by thaije** [comment]
See the repo from Emma here: https://github.com/xDaya/Co-Learing_Scenario

**Comment by jwaa** [comment]
@thaije this is still set as a Request. I believe it is a relevant feature and I think you as well. Do we want to bump it up to a Feature label? If so, is it possible for the upcoming v2.1.0 release?

**Comment by thaije** [comment]
Yes I also talked about this with Emma and it is still a request, so I converted it to a feature. It was indeed my intention to include this with release v2.1.0.

**Comment by thaije** [comment]
This is now possible by passing the `visualize_from_center` param for an object (`True` by default), like so: 
`builder.add_object([6,7], "block", visualize_size=5.0, visualize_from_center=False)`, which will place an object at location (6,7) with 5x the usual size, and visualized from the top left down. See the image below for an example result. 
Note the black square is drawn later, and indicates the size of 1 tile at location (6,7). As you can see the entire object has a size of 5x5 tiles and drawn from the top left down to the bottom right. 
![image](https://user-images.githubusercontent.com/2978372/118413203-60336100-b69e-11eb-8538-91be0e0c256c.png)

**Comment by thaije** [comment]
Bug: setting central point of visualization to `False` only works for objects, not for agents.
