### ISSUE TITLE
Context menu broken with updated pip packages

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#223]
**Describe the bug**
The context menu doesn't work when right clicking, or first selecting an agent and then right clicking in the view of an human agent. The error below is thrown. 

**To Reproduce**
Clone the matrx repository and master branch. Install with `python3 -m pip install --upgrade -r requirements.txt` to make sure all your packages are updated. Start with `python3 main.py`, start in `localhost:3000/god` and try to open a context menu in one of the Human Agent views.

**Expected behavior**
Context menu working.

**Stacktrace**
```[2020-09-08 15:20:46,736] ERROR in app: Exception on /fetch_context_menu_of_self [POST]
Traceback (most recent call last):
  File "/home/hal/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hal/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hal/.local/lib/python3.6/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/hal/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)
  File "/home/hal/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/hal/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hal/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/hal/Projects/matrx/matrx/api/api.py", line 445, in fetch_context_menu_of_self
    self_selected)
TypeError: 'NoneType' object is not callableMATRX paused through api
```

**Comment by thaije** [comment]
@jwaa Can you do a pip freeze and paste the results here for your working setup? I updated all my installations already and can't figure out which package causes the error.

**Comment by jwaa** [comment]
@thaije, that will sort of be an issue... Just got a new laptop and haven't been able to work on MATRX on it yet. So I have don't have a MATRX environment setup for you :(

Tried rerolling to the minimum versions in our `requirements.txt`? It also seems to be Flask related, so perhaps this one had a recent update (Flask updates tend to break things anyway)?

**Comment by thaije** [comment]
This didn't turn out to be a bug, just unclear when the user did something wrong. 
There were two causes: 
- trying to open the `context_menu_for_self` for an agent in an agent view throws the above error. This behaviour is expected, as a normal agent cannot be controlled by a human and thus doesn't have a `context_menu_for_self`. However preferabbly it should return a descriptive error message.
- In another project with the same error, someone added a human agent using  `worldbuilder.add_agent` instead of `worldbuilder.add_human_agent`. This didn't give errors except for when trying to open the context menu, which threw the error above. 

The second bullet is just a normal user coding mistake, but the first one should be fixed by making the error message more clear for the user and catching the error.
