### ISSUE TITLE
Chat dissappears to bottom of page for long chat messages

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#227]
**Describe the bug**
For a wide MATRX environment, once a long chat message is received the chat is pushed to the bottom of the page.

**To Reproduce**
See above

**Expected behavior**
Stay in view 

**Additional context**

Possible fix: add `flex: 1;` to `#chat`.

**Comment by jwaa** [comment]
@Thaije what do you mean with 'wide MATRX environment'?
