### ISSUE TITLE
Visualization terribly slow for host localhost

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#229]
**Describe the bug**
The visualization gets the MATRX visualization server URL from your browser. So if you go to localhost:3000/god, it will try to connect to the API via localhost:3001. However, this is terribly slow if you type in localhost, with 1 API call to MATRX taking between 50-400 ms. The weird thing is it is way faster if you connect via 127.0.0.1:3000 (also local), or your network api, (e.g. 139.63.77.143), only taking a couple ms. 

**To Reproduce**
Run default matrx and visualizer, start in the god view, and keep an eye on the network tab of the browser console. 

**Expected behavior**
Localhost should be just as fast as other urls, especially as localhost is easy to remember for most. 

**Screenshots**
For localhost:
![image](https://user-images.githubusercontent.com/2978372/95864886-462b4c00-0d66-11eb-977a-66d773308c84.png)

For 127.0.0.1: 
![image](https://user-images.githubusercontent.com/2978372/95865184-ab7f3d00-0d66-11eb-8ddc-01999b9ac222.png)

**Additional context**
This issue aligns with comments received from the first MATRX use for an experiment, where the laptop hosting the MATRX world was slow and laggy (accessed via localhost), while other computers connected to the PC via a dongle were fast (non-localhost).

**Comment by thaije** [comment]
The cause seems to be that for some computers localhost is routed via ipv6 as well as ipv4. First ipv6 is tried (which isn't configured for the flask server), followed by the ipv4. 127.0.0.1 is the ipv4 local ip, which circumfents this problem.

**Comment by thaije** [comment]
@jwaa good to know

**Comment by jwaa** [comment]
It seems we can do little about this then implementation wise, except giving this recommendation. Too bad! Though either way good to know.

**Comment by thaije** [comment]
Yes or we have to implement a more robust werbserver that uses ipv6. But I don't know how much work that is.
