### ISSUE TITLE
The team functionality combined with State is unclear

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#242]
**What is your question?**
I assumed that the team name is '' since that's what I see in the state. And that that code was showing that the agents are available all the time. Why is there even a team name if there's no team... May I suggest to remove defunct code...

But, how about get_agents()? Are you saying that this is also defunct code? As that suggests exactly the same , that agent objects remain visible.

**To what is your question related?**
- [ ] I am not sure if I should use MATRX.
- [ ] I have a question about the idea behind MATRX.
- [x] I don't know how to do something with MATRX.
- [ ] I don't know where to find something.
- [x] I think I found a bug, but I am not sure.
- [ ] I want to contribute, but don't know where to start.
- [ ] Something else.

**Aditional context**
These questions were raised in #241 and moved here to prevent offtopic discussions in an issue. These questions were raised by @Wouter1

**Comment by jwaa** [comment]
> And that that code was showing that the agents are available all the time. 

I don't know what you mean with "that code", could you elaborate?

> But, how about get_agents()? Are you saying that this is also defunct code? As that suggests exactly the same , that agent objects remain visible.

Why would this be defunct according to you? It returns all property dictionaries of all agents that were perceived by the agent. I am confused why you would think that agents always remain visible because `State` has a `get_agents()` method.

**Comment by Wouter1** [comment]
get_agents is working only for agents within range of visibility. This is not what I am expecting from the call. I'm expecting a list of all agent names or so, so that I can message them. 

Also note that in state.py, there is no documentation attached to the function. So users have to guess how this is working

>I am confused why you would think that agents always remain visible because State has a get_agents() method.
I'm confused by why you even mention  visibility.
Well, given your previous explanations, I now realize that these agents disappear out of view and that I have to change some settings, which will then modify also the behaviour of this function. This is all not trivial and not documented.

**Comment by Wouter1** [comment]
>I don't know what you mean with "that code", could you elaborate?

I was referring to state.py get_agents and get_team_members()

**Comment by jwaa** [comment]
> get_agents is working only for agents within range of visibility. This is not what I am expecting from the call. I'm expecting a list of all agent names or so, so that I can message them.

Yes, the `State` is always relative to what the agent perceives; it is the agent's world state similar as in MDP-like frameworks. For BW4T it might be convenient that all agents are always visible. Which can be set using the suggestion I gave you earlier that changes the sensing range for all agents to see others. The `filter_observation` method can be used to further prune this information.

However for many other cases this is not what you want. Imagine a game with friendlies and enemies. If all agents always perceive the others, they can cheat. As they know when a new enemy is spawned for instance. This is the reason why perception range is governed by MATRX but more use case specific options such as what kind of properties are relayed to the `decide_action` method is governed by you own agent implementation.

> Well, given your previous explanations, I now realize that these agents disappear out of view and that I have to change some settings, which will then modify also the behaviour of this function. This is all not trivial and not documented.

I am not sure where you refer to with "this function". I believe you refer to your own custom method, so I can't help you there nor comment on how much impact this knowledge has on you.

This is getting off topic again and it seems your original question is answered. So I close this issue for now. Feel free to respond if your original question was not answered sufficiently or open a new issue for any other questions.

**Comment by Wouter1** [comment]
I was not referring to my own methods.

What it boils all down to is that the state method is not documented.
Functions like get_agents are suggestive but do not perform as suggested by their name because of other undocumented properties of the state like visibility distances.
