### ISSUE TITLE
Places for links to the MATRX docs

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#243]
**What is your question?**
The docs! I never found more docs on matrx. Can a link to this be put at the top of the wiki maybe?

**To what is your question related?**
- [ ] I am not sure if I should use MATRX.
- [ ] I have a question about the idea behind MATRX.
- [ ] I don't know how to do something with MATRX.
- [ ] I don't know where to find something.
- [ ] I think I found a bug, but I am not sure.
- [ ] I want to contribute, but don't know where to start.
- [x] Something else.

**Additional context**
This question was originally raised by @Wouter1 in #241

**Comment by jwaa** [comment]
Thanks for the question! I need some more info to answer it.

> The docs! I never found more docs on matrx. 

I'm curious what other docs you found beside our main [reference](http://docs.matrx-software.com/en/master/). What do you mean with 'more' here?

> Can a link to this be put at the top of the wiki maybe?

Which wiki do you refer to? [This one](https://github.com/matrx-software/matrx/wiki)?

**Comment by thaije** [comment]
Maybe the tutorials page on the MATRX website was meant? https://matrx-software.com/tutorials/ 

There is a link to the docs on the website to the docs, under learn > API Reference. I added another link to the top of the /tutorials page as requested.

**Comment by Wouter1** [comment]
I don't know but I failed to find this documentation until it was mentioned here. I think it could use some more prominence.

**Comment by thaije** [comment]
Closing this issue as a link was added to the tutorials page, it is present in the menu, and we will mention it in the MATRX beginner tutorial.
