### ISSUE TITLE
How to do I get the IDs of agents to send messages to?

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#244]
**What is your question?**
How can I get the object IDs of agents I want to send a message to?

**To what is your question related?**
- [ ] I am not sure if I should use MATRX.
- [ ] I have a question about the idea behind MATRX.
- [x] I don't know how to do something with MATRX.
- [ ] I don't know where to find something.
- [ ] I think I found a bug, but I am not sure.
- [ ] I want to contribute, but don't know where to start.
- [ ] Something else.

**Additional context**
This question is raised often, caused by the fact that object IDs are generated when the `GridWorld` instance from a `WorldBuilder`  is first started. This pevents MATRX users from providing these or some other identifier to the constructor of an `AgentBrain` (e.g., effectively telling the agent upfront which other agents should receive messages). 

This question was raised in issue #241 by @Wouter1, moved here to keep that issue on topic and to have the answer as a future reference.

Note that a future update of MATRX is likely to fix this hassle.

**Comment by jwaa** [comment]
This is an issue encountered more often: If an agent does not see an object (e.g., another anget) but does need to interact with it (e.g., send a message), how does it get the object ID to do this if these IDs are generated on runtime?

The, very inconvenient but simplest workaround, is that you let the agent perceive other agents with infinite range by setting/altering its `SenseCapability` you provide when adding an agent. For example, to add an agent that always sees other agents:

```Python
from matrx.grid_world AgentBody
from matrx.agents import SenseCapability
import numpy as np

sense_capability = SenseCapability({AgentBody: np.inf})

```

@Wouter1 Since you are working with the BW4T code, on [this line](https://github.com/matrx-software/bw4t/blob/dev/builder.py#L139) the sense range for other agents is set. By changing the value on [this line](https://github.com/matrx-software/bw4t/blob/dd78e16fd61e8223f304cb4af098285ac9e11148/builder.py#L49) to infinite you achieve that all agents can see eachother all the time.

Now that we have set an agent to see all other agents, `State.get_agents()` method can be used to return all agents. This can for instance be done at the first time the `AgentBrain.filter_observations(...)` is called. In the same place all agents can also be removed from the `state` if in fact the agent should not use this info to decide its action on. For instance by either removing all agent objects or based on their distance with the help of the state's distance map: `state.get_distance_map()`.

I admit that this is very tedious and overly complex. As such we are thinking of using agent and object names instead of object IDs. This would require all names to be unique, but names are known before starting a `GridWorld` instance and thus names of agents or objects can simply passed to the constructor of an agent.

**Comment by Wouter1** [comment]
Thanks jasper

Another option is that we require all agents to broadcast their ID. 

Your option works always but also it might have some other side effects that are less desirable, eg you now loose the need for agents to communicate where they are going, because you can see them anyway

**Comment by jwaa** [comment]
Broadcasting the ID also works, some MATRX users indeed go for that route. Seems to work fine indeed!
