### ISSUE TITLE
Document action 'duration' 

### ISSUE THREAD

**Issue by Wouter1** [matrx-software/matrx#247]
**What is your question?**
Documentation on action 'duration' field is unclear
what happens if agent does this
tick 1:  move north, duration=5
tick 2:  move south, duration=4
tick 3:  move north, duration=3
tick 4:  move south, duration=2

Naively, I would assume all these actions are executed at once, all at the 5th tick.
But in which order?

**Comment by thaije** [comment]
Hey @Wouter1, do you have a link to the documentation / function in particular which you find unclear? Or is there a complete lack of any documentation on it? 

In practice, the action duration works in that once an agent decides to do an action by returning this from the `decide_on_action` function, e.g. move north, with an action duration of 5, that agent will be "busy" for 4 ticks, and do the action on the 5th. The agent being busy is indicated with the gears animation in the frontend. 

What this means for the agent is that when the agent is busy with an action, the agent can only perceive the world, but not decide on a new action: only [`filter_observations`](https://github.com/matrx-software/matrx/blob/master/matrx/agents/agent_brain.py#L110) is called for agents that are busy with an action, and [`decide_on_action`](https://github.com/matrx-software/matrx/blob/master/matrx/agents/agent_brain.py#L164) is skipped. In that manner the situation you propose is impossible, as the agent is blocked from deciding on any new actions once it has initiated an action that takes multiple ticks.

**Comment by Wouter1** [comment]
Here

http://docs.matrx-software.com/en/master/sections/_generated_autodoc/matrx.actions.object_actions.RemoveObject.html

>The default duration of this action in ticks during which the matrx.grid_world.GridWorld blocks the agent performing other actions. By default this is 1, meaning that this action will take both the tick in which it was decided upon and the subsequent tick.

What I was missing is exactly what you are describing to me now. Particularly that  decide_on_action will not be called for this duration.

Thanks for the additional info. Maybe this should be on the page I mentioned above.

**Comment by thaije** [comment]
@Wouter1 Good to hear that that was the information you were looking for. I will leave this issue open and changed the issue a bit such that it contains adding the documentation on the action duration more clearly as you describe. 

The new documentation would include: 
- Adding a [tutorial ](https://matrx-software.com/tutorials/) on the action duration. 
- Either updating the documentation of the action duration in each function where it is used to include the information I described above, or linking to the tutorial.

**Comment by Wouter1** [comment]
@thaije  thanks. I would reverse the priority. First prio is to have the docs in the code itself. This is what a programmer should see right away when he writes the code. Unfortunately python is not working nicely with my (Eclipse) GUI like java does but ideally he should not need any tutorials, just get the pop-up docu and then pop in what he needs.
