### ISSUE TITLE
state throwing exception related to 'decay'

### ISSUE THREAD

**Issue by Wouter1** [matrx-software/matrx#250]
**Describe the bug**
I get uninformative stacktrace from somewhere deep inside matrx. See below.

**To Reproduce**
I run the "naive_agent" from our BW4T-Matrx repo . Rev. 392f177...

**Expected behavior**
No throws from matrx code

**Stacktrace**
```
Traceback (most recent call last):
  File "C:\Users\wouter\git\BW4T-Matrx\main.py", line 18, in <module>
    world.run(builder.api_info)
  File "C:\Users\wouter\git\BW4T-Matrx\venv\lib\site-packages\matrx\grid_world.py", line 230, in run
    is_done, tick_duration = self.__step()
  File "C:\Users\wouter\git\BW4T-Matrx\venv\lib\site-packages\matrx\grid_world.py", line 640, in __step
    filtered_agent_state, agent_properties, action_class_name, action_kwargs = agent_obj.get_action_func(
  File "C:\Users\wouter\git\BW4T-Matrx\venv\lib\site-packages\matrx\agents\agent_brain.py", line 546, in _get_action
    self.state.state_update(state)
  File "C:\Users\wouter\git\BW4T-Matrx\venv\lib\site-packages\matrx\agents\agent_utils\state.py", line 65, in state_update
    for obj_id, decay in self.__decays.items():
RuntimeError: dictionary changed size during iteration
```

**Additional context**
All elements in the stacktrace point towards matrx so this must be some issue in matrx itself.
And if the root cause is some bug in an agent, then matrx should have caught it or showed a concise error message pointing out the root cause instead of throwing this way.
The other agents in our repo seem to work fine. I'm not the programmer of naive_agent so I can't help much regarding that.

**Comment by thaije** [comment]
@Wouter1 thanks for mentioning this issue. Do you have some additional information on how to reproduce the error? You mentioned this occurs for the [MATRX implementation of the BW4T task ](https://github.com/matrx-software/bw4t/tree/dev)for the naive_agent. I am less familar with our implementation of the BW4T task and our implementation than @jwaa, but I see we only provide a [textual representation](https://github.com/matrx-software/bw4t/blob/dev/agent_stub.py#L46) for the reasoning of the naive agent, but no real working agent itself. Thus the naive agent is one you implemented yourself based on the description, is that correct? If so , could you provide the code for the naive agent?

**Comment by Wouter1** [comment]
@thaije naive_agent is a full implementation available on our repository.
Jasper has access to the repo. 

The version I refer to is on our university server 

Sorry that I don't have a shorter how-to-reproduce. At top level what I do is, just select the failing agent in the builder (import it) and run the world.

**Comment by Wouter1** [comment]
I notice in places in our agent codes something like this
```
        new_state = state.copy()

        for obj in list(state.keys()):
            if 'Block_in_room' in obj:
                # Remove colour
                new_state[obj]['visualization'].pop('colour')

        self.state_tracker.update(new_state)
        return new_state
```

I think this is modifying the state as provided by matrx

Seems to me that that code is bad; but also I see that it would be bad if matrx would be vulnerable to such changes.

Could this explain this problem or the other problem I mentioned?

**Comment by jwaa** [comment]
A quick glance indeed indicates a bug in `State`. Could you provide us some information on the criticality of this issue for you? I have quite limited time this week, this would help me prioritize it.

Regarding your code snippet; it is safe to remove or add things to the `State` of an agent. These are just "local" to the agent and do not cause the world to change or anything. 

However, the exception is not a good thing so we will look into that. Thanks for reporting!

**Comment by jwaa** [comment]
Based on our meeting @Wouter1 the priority of this bug is medium. As it is not a dealbreaker for your code.
