### ISSUE TITLE
Logging send messages does not work nicely with step()

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#254]
**Describe the bug**
This is a functional bug.

The current logging functionality of MATRX allows `AgentBrain` to override a `get_log_data` method that is forwarded to all `GridWorldLogger` instances added to a world. However, if you want to create a logger that logs the messages an agent send this is not possible. 

You would expect that you can format and return the `AgentBrain.send_messages` attribute in the `get_log_data`. However, this list is emptied at the end of every tick by the messaging system. While the logging functionality is called at the start of the `GridWorld.step()` method. Thus it means that when you are in `get_log_data` the `send_messages` attribute is always empty; either it is not filled, or its content was already removed at the end of the previous tick.

**To Reproduce**
This is a functional bug and is easiest to reproduce by printing the content of `AgentBrain.send_messages` in the `AgentBrain.get_log_data` for an `AgentBrain` that sends messages.

**Expected behavior**
A way that allows an `AgentBrain` to access past send messages, at least those messages that were send in the previous tick.

**Screenshots**
N/A

**Stacktrace**
``If applicable, copy the entire stack trace here.``

**Additional context**

**Comment by Wouter1** [comment]
Yes thanks for reporting. Current workaround that I use:

Store a copy of the messages in the agent, both after the call to decide_on_action and in filter_observations (possible because our agents do not override these directly)

 in the agent's get_log_data function, use the copy to report on the messages. These are messages from the previous tick, so you may have to compensate the log file or post-processor now for this lag.

**Comment by thaije** [comment]
This seems to me to be two separate issues: 
- Not having access to sent messages in the (human) agent brain
- Not being able to log messages sent by agents 

The first issue is related and might be solved by the fix described in issue #201. In that issue the need for a message history is described for messages received and sent by an agent, that is accessible from within the agent brain. I think that solution would solve the current issue as well. 

The second issue of not being able to log messages is only true if you want to use the agent logger with `get_log_data`. If you use a general logger that has access to the `GridWorld`, you can access the [`MessageManager`](http://docs.matrx-software.com/en/master/sections/_generated_autodoc/matrx.messages.message_manager.MessageManager.html#matrx.messages.message_manager.MessageManager) which contains all the messages ordered by tick for every agent. 
As an example, I created [this branch](https://github.com/matrx-software/matrx/tree/254_log_sent_messages) in which the example case all agent messages are logged every tick in a Results folder. Here is the [message logger example](https://github.com/matrx-software/matrx/blob/254_log_sent_messages/matrx/logger/log_messages.py), in which the message **content** is logged, but (as example) also the **entire** Message object as json.
