### ISSUE TITLE
API attributes set as "private"

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#255]
**Is your feature request related to a problem? Please describe.**
I noticed that a MATRX user adjusted the attributes of the api.py, to try and disable the visualization. This is not something a regular MATRX user should meddle with, but this is not clear since these attributes are not prefixed with a double underscore (denoting "private").

**Describe the solution you would like**
Every attribute in api.py prefixed with double underscores.

**Describe alternatives you have considered**
A clear documentation mentioning that these variables are  not intended to be altered (either because they can result in instabilities or because they are overwritten on runtime anyway). Though this can be done as well.

**Additional context**
Noticed when receiving a question on how to disable the default visualization server (which is not clear how to do this btw).

**Comment by thaije** [comment]
All functions and attributes of the API are either set to private (__) or module-private (_). The latter in case the gridworld needs access to the function or attribute (which are quite a few).
