### ISSUE TITLE
Setting for starting MATRX Paused / Unpaused

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#256]
**Is your feature request related to a problem? Please describe.**
By default MATRX starts paused when a frontend is enabled, requiring the user to press play in the god view 
I want to start MATRX with frontend but have it start immediatly without having to press play. 

**Describe the solution you would like**
Add an option `matrx_paused` that can be added to the API info. 

Example code for the [example MATRX case](https://github.com/matrx-software/matrx/blob/master/matrx/cases/vis_test.py#L80):
```
# run each world
for world in builder.worlds(nr_of_worlds=nr_of_worlds):
    builder.api_info['matrx_paused'] = False
world.run(builder.api_info)
```

**Describe alternatives you have considered**
Running without frontend (in that case MATRX does not start paused).

**Comment by thaije** [comment]
See https://github.com/matrx-software/matrx/commit/1b68dfaf3e36189c4a26131f87fffbd190377402

**Comment by Wouter1** [comment]
@thaije I tried what you wrote but it did nothing to start the world.

Then I looked into the matrx code itself and I see that there is an additional underscore 
```
                api._matrx_paused = True if '_matrx_paused' not in api_info else api_info['_matrx_paused']
```

So it seems I need to set
```
    builder.api_info['_matrx_paused'] = False
```

If I use that, I can indeed access the GUI.
So I got it working. 

But is this intended this way? Or should that be fixed?

**Comment by thaije** [comment]
Ah thanks for notifying of that. The underscore is an unwanted artifact from reformatting the API parameters. For now you can use _matrx_paused, and we'll remove the underscore in a next release.

**Comment by thaije** [comment]
@Wouter1 the option has been renamed to `matrx_paused` in v2.0.7
