### ISSUE TITLE
Software flow

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#26]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Wednesday Jan 22, 2020 at 12:53 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/25_

----

Determine and document the flow on how MATRXS developers use Git, this repo, deployment, testing, issues handling and communication. These should contain clear and transparent agreements that fit our way of working without creating (too much) overhead.

**Comment by jwaa** [comment]
Done, added to the How To Contribute guide:
https://matrx-software.com/how-to-contribute-to-matrx/#contribute-workflow

We follow the same workflow as described in this blogpost: 
https://nvie.com/posts/a-successful-git-branching-model/
