### ISSUE TITLE
god mode view broken

### ISSUE THREAD

**Issue by Wouter1** [matrx-software/matrx#261]
**Describe the bug**
 to test if our code is still working with the new matrx (it was all working with 2.0.4) , I run the BW4T agents using the new matrx 2.0.5 (I used pip install --upgrade).

I go to localhost:3000 , select god mode and start the simulation.
Nothing happens in the god view. However I can see that agents are doing actions as expected and they even complete the BW4T (I can see the final message "Scenario stopped through api" and "Done!".

if I click on refresh, the god view goes grey, it is not refreshing at all. Only the top border with the "Matrx" logo and buttons is there.

**To Reproduce**
Run BW4T with eg planninagent3

**Expected behavior**
God view shows how the agents run through the maze

**Stacktrace**
In firefox debug mode I can see an error
```
Uncaught typeError: document.getElemenetById(...) is null
open_chatroom .. toolbar.js:385
process_messages ...toolbar.js:593
draw: ....gen_grid.js:80
world_loop ......loop.js: 227
```

**Comment by Wouter1** [comment]
------ Original Message ------
From: "Pradeep Murukannaiah" <P.K.Murukannaiah@tudelft.nl>
To: "Wouter Pasman - EWI" <W.Pasman@tudelft.nl>
Sent: 2/8/2021 11:47:00 AM
Subject: Re: god-view issue

Jasper
 
If someone picked it up already, that’s fine. We don’t need to write to Jasper.
 
--Pradeep
 
﻿On 08/02/2021, 11:45, "wpasman" <w.pasman@tudelft.nl> wrote:
 
    Hi Pradeep,
 
    I can see on the ticket
    https://github.com/matrx-software/matrx/issues/261
 
    that thaije already picked it up
 
    Do you still want to inform jasper?
 
    Wouter

**Comment by thaije** [comment]
Thanks for notifying! I put a hotfix for the bug in v2.0.6.

**Comment by Wouter1** [comment]
@thaije  Thanks for fixing this so quick!
Can I use ```pip install --upgrade``` or do I need to do something else to get this fix?

**Comment by thaije** [comment]
@Wouter1 You're welcome :) Yes that should do the trick, and possibly also clearing your cache.
