### ISSUE TITLE
Suppress outputs when disabling matrx API

### ISSUE THREAD

**Issue by mlpeschl** [matrx-software/matrx#277]
**Is your feature request related to a problem? Please describe.**
Sometimes I like to run many simulations without making use of the matrx API for AI training purposes. However, each time the world builder is called, it outputs a list of tasks (creating agents, placing objects, etc...) which introduces unnecessary prints to the console for this purpose.

**Describe the solution you would like**
I saw that there is a verbose parameter in the world builder class, so I think it would be nice if this parameter could also be used to completely suppress these kind of print statements.

**Describe alternatives you have considered**
What I have been doing for now is introduce a workaround that completely suppresses all print outputs inside a specific block of code by using the os and contextlib packages:

```python
with open(os.devnull, "w") as f, contextlib.redirect_stdout(f):
    builder = avoid_builder(run_matrx_api=False, run_matrx_visualizer=False, tick_speed=0)
    builder.startup()
    world = builder.get_world()
    world.run(api_info=builder.api_info)
    builder.stop()
```
This definitely works, but it might not be the most beautiful solution, especially when you want to print out certain other things that occur inside the simulation during world.run().

**Additional context**
-

**Comment by jwaa** [comment]
@mlpeschl Thank you for your very reasonable request! I will take it up with @thaije to see if we can plan it in a next release.

**Comment by thaije** [comment]
@jwaa What would you think is the best solution for being able to suppress all output? I see a couple of solutions:
- Completely suppress all output when verbose=false. 
- Make verbosity levels with "debug", "info", "error" or something like that. 
- Suppress all output when the API is set to false. 

Personally I would think the second option is the cleanest or clearest with the default being a "info" output level, however it is a bit more complex to implement. The third option is also nice, except for that it might not be very intuitive to the user that disabling the API results in all output being suppressed. The first option is an all or nothing decision and might not be really desirable for the average user.
