### ISSUE TITLE
wall_visualize_opacity parameter in add_room() not working

### ISSUE THREAD

**Issue by centeio** [matrx-software/matrx#279]
**Describe the bug**
The parameter wall_visualize_opacity in add_room() (world_builder.py) does not seem to be working. Tried values 0.0 and 1.0 and still full opacity.

**To Reproduce**
```
        builder.add_room(top_left_location= (room_top_left_x, room_top_left_y), width=w, height=h, name=room_name,
                         door_locations=door_locs, doors_open = True,
                         wall_visualize_colour=wall_color,
                         with_area_tiles=True,
                         wall_visualize_opacity=0.0,
                         area_visualize_colour=room_color, area_visualize_opacity=0.0)
```

**Expected behavior**
Walls not visible. Background image fully visible.

**Additional context**
Also, it would be nice to have opacity for the door too. I am trying to create an aisle (instead of a room) with objects, and already have a background image with the walls (in certain colors, which can be reproduced in the code, but I'd prefer not to...).

**Comment by jwaa** [comment]
@centeio thanks for reporting!

The request for door opacity sounds a good one (and consistent with other methods in the `WorldBuilder` as well). It is already included in your request #280. 

Regarding the bug that is indeed strange, and I can replicate it. Will look into it and come back to you when we have a solution and possible workaround until the hotfix is released.

**Comment by jwaa** [comment]
Found the bug! Sadly it is a bug in the core of the `WorldBuilder` that affects potentially many objects (made a report for it #281). Though there is a quick (temporary) fix for it that can be easily done for the `Door` and `Wall` objects you are using. 

The elaborate and general fix might take one or two weeks depending when I can find the time in the weekend. I can do the quick fix this week I hope. So the question is how quick you need this solution? Hopefully the answer is not "yesterday" :p

**Comment by jwaa** [comment]
Noticed we already had a bug report for the general issue: #173...
Just shows that it might be time to fix it!

**Comment by centeio** [comment]
@jwaa thank you for your prompt answer!

I think I have some time (let's say 3 weeks), as this bug is regarding the visuals, so it does not stop the rest of the implementation/testing. Let me know how feasible it is, or whether I should find a workaround! Thanks.

**Comment by jwaa** [comment]
I will get back to you to see if we can plan a minor release within 3 weeks. We will combine this issue, #280 and some others in it. If you have any other requests or bugs you know of; feel free to post them and perhaps we might be able to include those as well.
