### ISSUE TITLE
Allow Door change of color and opacity

### ISSUE THREAD

**Issue by centeio** [matrx-software/matrx#280]
**Is your feature request related to a problem? Please describe.**
I want to create aisles (with blocks) instead of rooms, but I thinking about doing it through the add_room() function. However, the doors would be always open (no problem, this is what I want), but they are this green I did not choose.

**Describe the solution you would like**
I see Door has the option of choosing the color already, it would be good to make it available as add_room() parameter.

**Additional context**
The idea is to create a supermarket with aisles, instead of rooms, but they also have blocks.
![Method Draw Image (1)](https://user-images.githubusercontent.com/15066391/115369629-99c09b80-a1c8-11eb-8453-e991a7fe8ab8.png)

**Comment by jwaa** [comment]
@centeio Thanks for the request! Also nice to see your MATRX world, love the idea to use MATRX to model a supermarket :)

If I understand correctly you request to add two properties to the `WorldBuilder.add_room` method, such that its signature becomes:

```python
    def add_room(self, ..., door_open_colour="#006400", door_closed_colour="#640000", ...):
        ...
```

Where `door_open_colour` and `door_closed_colour` follow the same usage as the `Door` [constructor](https://github.com/matrx-software/matrx/blob/93b00b6e74d2fdcd3bc986d18d044f7d8bf0999c/matrx/objects/standard_objects.py#L48).

Is this a correct interpretation? If so, we will plan it in a release. How urgent do you need it?

**Comment by centeio** [comment]
Since we're here, and connected to #279, do you think it's possible to also add the opacity?

```
def add_room(self, ..., door_open_colour="#006400", door_closed_colour="#640000", door_open_opacity=1.0, door_closed_opacity=1.0 ...):
        ...
```
I'll answer the same and ask if it is possible to implement it within 3 weeks?

**Comment by jwaa** [comment]
Yes! That will be very much possible. Forgot to add them :)

Regarding the timeframe; I will look at it together with @thaije to see if three weeks is doable for us. Will get back to you this week!

**Comment by jwaa** [comment]
Together with #281 this is now solved. To make it easier, I added explicit variables in the `WorldBuilder.add_room(...)` for the door's colours and its opacity. These are variables for all doors you add to a room.
