### ISSUE TITLE
Arguments not passed correctly by WorldBuilder

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#281]
**Describe the bug**
The `WorldBuilder` uses reflection to check what arguments are passed when creating a world object (see [this line](https://github.com/matrx-software/matrx/blob/93b00b6e74d2fdcd3bc986d18d044f7d8bf0999c/matrx/world_builder.py#L2259) and onwards). This is used to pass all arguments to the given object's class. However, many edge cases are ignored when dealing with a subclass of `EnvObject`.

A concrete example of such an edge case is when a [mandatory property]() is given according to `GridWorld` (e.g., `visualize_opacity`) but that is not an actual argument of the subclass's constructor. In that case the argument is just ignored instead of passed in the subclass constructor's `kwargs`.

The method is just overly complex and thus missing these edge cases. Besides, it is quite hard to maintain...

**To Reproduce**
Run this code snippet, and you will observe that the opacity of the `Wall` objects are not set correctly:

```python
def test_builder(opacity, run_matrx_api, run_matrx_visualizer, tick_speed):
    builder = WorldBuilder(shape=[9, 10], run_matrx_api=run_matrx_api, run_matrx_visualizer=run_matrx_visualizer,
                           visualization_bg_img='', tick_duration=tick_speed,
                           simulation_goal=500)
    builder.add_room(top_left_location=[0, 0], width=9, height=10, name='Wall_Border', wall_visualize_opacity=opacity)

    return builder


if __name__ == "__main__":
    opacity = 0.5

    builder = test_builder(opacity, run_matrx_api=True, run_matrx_visualizer=True, tick_speed=1)
    builder.startup()
    world = builder.get_world()
    world.run(api_info=builder.api_info)
    builder.stop()

```

**Expected behavior**
For all arguments to be processed correctly, instead of being ignored.

**Screenshots**
The walls with an "opacity of 0.5". As you can see; it has no effect.
![afbeelding](https://user-images.githubusercontent.com/6059315/115419697-d311ff00-a1fa-11eb-91f6-3de5006516fd.png)

**Stacktrace**
N/A

**Additional context**
This is an issue that came across quite often in the past already. It never got fixed though. The workaround we chose all those previous times was to include the arguments in the subclass's constructor which fixes this. Though this forces all MATRX users to set *all* arguments explicitely instead of using `**kwargs` and passing that to its super-classes.

**Comment by jwaa** [comment]
Duplicate of #173.

**Comment by thaije** [comment]
@jwaa good point, that issue indeed sounds familair. Do you have an idea for a good solution?

**Comment by jwaa** [comment]
Yes! The only point this was done was to catch a missing but required argument in the `WorldBuilder`. This opposed to let the exception be raised from the object's constructor in the default Python format (e.g. `missing argument`).

Where it goes wrong that the inspection includes and checks for a lot more then required arguments. Making it overly complex and also very sensitive to edge cases. Instead I would propose to dial it down to just the following (in pseudo code):

```python
obj_class = settings["class"]
given_args = get_constructor_arguments(settings)
mandatory_args = get_class_arguments(class)
all_args_given = all([arg in given_args for arg in mandatory_args])
if not all_args_given:
    raise Exception("Hello, you forgot a required argument!")
else:
    obj = obj_class(**given_args)

return obj
```

**Comment by jwaa** [comment]
I noticed you did this fix in the continuous bug fixing branch instead of an issue branch. This might prove to be sub-optimal in the future. As this bug fix is now blocking any other hotfix that might be needed. So what I created an issue branch for this one from dev after merging the continuous bug fixing branch into dev.

@thaije I ran some tests (see the newest commit on this issue branch `test_obj_arguments`). It seems to work fine to a large extent, except that it is now required to always put a `**kwargs` into your custom objects constructor. Since the builder now tries to pass arguments (e.g., `is_movable`) to that constructor and it fails when those are not explicitly in the constructor and when there is no **kwargs to catch them. 

I think this is caused because the arguments from the builder are just added to the arguments that are eventually passed to the object constructor. In my pseudo code this is the reason why only the `given_args` are passed which are the arguments that are actually part of the constructor. 

However, the issue with that is that if there is indeed a **kwargs, any custom properties set through the builder are not passed! So perhaps we should add a check to see if **kwargs is present or not, and decide based on that whether it is possible to pass more then just the arguments in the constructor. However, this feels like over complicating things just to support a million ways to set custom properties (through constructor and through the builder).

**Comment by thaije** [comment]
Thanks for checking it out! And also I fully agree with the branching you did. 

With regards to the `**kwargs` etc, you are right, however I don't see it as an issue. If you pass arguments to a constructor of an object, the object should be able to catch those. If you pass 4 arguments to an object, but defined only 3 of those in the constructor, it is counter-intuitive if that last argument quietly disappears. It would than be better in my opinion to be explicit and just throw an error if these arguments cannot be processed by the object constructor.

In my opinion, the fault is with the builder. Why does the builder pass so many arguments to any object, even when their value is `None`? Isn't it simpler and more intuitive if the builder only passes arguments to the object constructor that were set by the user or have an actual value? In that way, you don't need the `**kwargs` for every (custom) object if you don't use those arguments. And if you do want to set some of those arguments, just add the argument or `**kwargs` to the constructor, which isn't such a problem either right? In my opinion it's better to be explicit, than to have arguments quietly disappear.

**Comment by jwaa** [comment]
I agree with all of this! The trouble is that we support the addition of custom properties through just passing them to the builder. However for that function to work a **kwargs is needed in the (custom) object classes. So my issue is more that we have so many ways of doing this: at the custom constructor, with the add_property method, through the builder and through the super call of the EnvObject... 

So if we want to throw an exception, we might just as well require that any custom object has its properties defined as (keyword) arguments in its constructor. At least as long as these properties differ when added with the builder. Otherwise they can just be defaulted in the custom object's dictionary.

Though maybe this breaks things for people? Perhaps set a deprecation warning and remove it in v2.3?

**Comment by jwaa** [comment]
@thaije I found a bug with this!

Remember that we once had the idea of a set of defaults you could adjust? It is still there in the `defaults.py` file. This is used on [this line](https://github.com/matrx-software/matrx/blob/93b00b6e74d2fdcd3bc986d18d044f7d8bf0999c/matrx/world_builder.py#L1128) to set the `is_movable` to a value. Causing it to be passed to the constructor of objects, resulting in:

`` TypeError: __init__() got an unexpected keyword argument 'is_movable'``

This happens when you try and run the BW4T test world in `main.py`:

```python
if __name__ == "__main__":
    cases.run_bw4t()
```
