### ISSUE TITLE
How to adjust the chat to support buttons instead of free text?

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#282]
**What is your question?**
As the title states, is it possible to have buttons in the frontend instead or in addition to the textfield for sending messages to other (human)agents in MATRX?

**To what is your question related?**
- [ ] I am not sure if I should use MATRX.
- [ ] I have a question about the idea behind MATRX.
- [x] I don't know how to do something with MATRX.
- [ ] I don't know where to find something.
- [ ] I think I found a bug, but I am not sure.
- [ ] I want to contribute, but don't know where to start.
- [ ] Something else.

Question came from Ruben and Carolina from the TU Delft.

**Comment by thaije** [comment]
Yes this is possible, but requires editing the default MATRX frontend. I will create a tutorial and add it to the website: https://matrx-software.com/tutorials/

**Comment by Stephenkruk** [comment]
Hi, I'd like to know far progress is with this documentation feature, as I like to use this in my research. Thanks

**Comment by jwaa** [comment]
Hi @Stephenkruk, this issue is part of the upcoming release to v2.1.0 which is planned to be deployed today or tomorrow. @thaije could give you more information on progress.

**Comment by thaije** [comment]
See the tutorial here: https://matrx-software.com/docs/tutorials/customizing-matrx/
