### ISSUE TITLE
Facilitate using images for visualizer outside of visualizer folder 

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#30]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thaije](https://github.com/thaije)**
_Tuesday Jan 28, 2020 at 10:14 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/29_

----

For the visualization, images are served from the matrxs_visualization/static/.. folder. When MATRXS becomes a python package, it does not make sense for users to have to put their images in that folder of the python package. 
As such, figure a way out to serve images via the Flask frontend visualization server from outside of the Flask app directory.

**Comment by matrx-software** [comment]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thaije](https://github.com/thaije)**
_Tuesday Jan 28, 2020 at 10:24 GMT_

----

[Related issue on so](https://stackoverflow.com/questions/26971491/how-do-i-link-to-images-not-in-static-folder-in-flask/26972238#26972238 )
[Relevant Flask function](https://flask.palletsprojects.com/en/1.0.x/api/#flask.send_from_directory)

**Comment by thaije** [comment]
I solved it using the official Flask recommended way, as described in the links above. There are now 2 options for providing images / media for agents:
- Image file defined in the static folder of the matrx_visualizer package. These files should start with `/static/`. 
- Images from outside the MATRX package. To use such an image, the user should pass the 'media_folder' parameter to the factory.startup() function in main.py. This can for instance be pointed to the folder in which the main.py is put (e.g. see here for an [example ](https://github.com/matrx-software/matrx/blob/%2330_visualizer_images_from_outside_visualizer_folder/main.py#L10)). The user can then very easily point towards an image in that folder, which can also be placed in one or multiple subfolders, such as by defining `img_name="/img/agent_external.gif"`. [See here for an example.](https://github.com/matrx-software/matrx/blob/%2330_visualizer_images_from_outside_visualizer_folder/matrx/scenarios/new_vis_test.py#L52)

@jwaa How is this solution?

**Comment by jwaa** [comment]
Love it! Will merge it with dev.

A potential future improvement for ease of use would be to ommit the need of providing a path at all. Just search whether the file name is in one of the submitted folders (where user folders have preference over the MATRX static folder). The translation from filename to path can be done by the `WorldBuillder`. Made a request for that; #114
