### ISSUE TITLE
Grabbing and dropping an object changes the obj ID

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#310]
**Describe the bug**
When an object is grabbed (and thus removed from the world) and then dropped (added to the world again) its object ID changes

Most likely this happens because when the object is added to the world again, it is treated like a new object and ensured a unique object ID. The old object ID was already taken, so it gets a new one: https://github.com/matrx-software/matrx/blob/master/matrx/grid_world.py#L514

A solution would be to add a boolean called `ensure_unique_id` to the `register_env_object` function so that for adding a picked up object it could be turned off. 

**To Reproduce**
Make a world where an object is grabbed and dropped, and check the obj ID before and after.

**Expected behavior**
The object ID remains the same

**Comment by jwaa** [comment]
A possible alternative solution is to only generate an ID if an object does not have one yet.

**Comment by thaije** [comment]
Fixed by adding an `ensure_unique_id` boolean to the `register_env_object` such that the `ensure_unique_id` is not called when dropping an object in the world again. 
Checking if the object already had an obj ID didn't work, as all objects already have an obj ID, and `ensure_unique_id` only fixes those of objects before registering in the gridworld.
