### ISSUE TITLE
State get_closest_with_property function doesn't give closest object

### ISSUE THREAD

**Issue by BirgitvdS** [matrx-software/matrx#317]
**Describe the bug**
self.state.get_closest_with_property("treatment_need") function does not give you the closest object with property "treatment_need" but in stead gives you all objects with property "treatment_need"

**To Reproduce**
use the function self.state.get_closest_with_property("treatment_need")
from https://github.com/matrx-software/matrx/blob/5b36ef1018e85172dc88cd7467e3087ef94c58ba/matrx/cases/bw4t/bw4t_agents.py

**Expected behavior**
it should give only the closest object with property treatment_need, not all of them.

**Comment by thaije** [comment]
@BirgitvdS I wasn't able to replicate this in the MATRX v2.1.3. If do a `self.stage.get_closest_with_property("some_property_that_multiple_objects_have")`, I get a list back with only the closest object with that property. 

Do you have a branch with your code that shows the issue? And did you try upgrading to the latest MATRX version (pip install --upgrade matrx)?

**Comment by thaije** [comment]
I tested this again and it seems to work, so I'm closing this issue. 
If this does stay an issue, please feel free to reopen the issue with some additional description on the issue.
