### ISSUE TITLE
Customizable properties not being passed for custom objects

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#321]
**Describe the bug**
All non `EnvObject` objects, such as a `Door`, do not listen to the `customizable_properties` parameter when set from a scenario file using `world_builder.add_object([0,0], name='door', customizable_properties=['some_property'])`. 
The reason being that the `customizable_properties` property gets special treatment, which works for `EnvObjects`, but it is forgetten to be passed along for objects of a specific class. 

You can see that it is specified [here](https://github.com/matrx-software/matrx/blob/master/matrx/world_builder.py#L2231) and for `EnvObject` they are passed [here](https://github.com/matrx-software/matrx/blob/master/matrx/world_builder.py#L2239), but for other objects they are never passed anymore (see [here](https://github.com/matrx-software/matrx/blob/master/matrx/world_builder.py#L2265)). 

**To Reproduce**
E.g. add a room with the [`add_room`](https://github.com/matrx-software/matrx/blob/master/matrx/world_builder.py#L1901) function and pass along the `door_customizable_properties=['img_name']`. Then attempting to change the image of that door in an action is ignored. 

**Expected behavior**
`customizable_properties` being set in a scenario file should be passed and not ignored. 

**Stacktrace**
There is no stacktrace, but MATRX just ignores any attempt at changing a property that it thinks you did not specify as being customizable.

**Comment by thaije** [comment]
## Solution 1: patch `customizable_properties` 
A solution could be to add the customizable_properties to the list of properties [on this line](https://github.com/matrx-software/matrx/blob/master/matrx/world_builder.py#L2265) like so: 
`given_args = {**mandatory_props, **custom_props, 'customizable_properties': settings['customizable_properties']}`

And also adding another check [here](https://github.com/matrx-software/matrx/blob/master/matrx/world_builder.py#L2275) to also leave customizable_properties out if it is an empty list (which is the default), like so: 
``` python
# combine the given arguments and any required arguments with defaults that were not specified by the user
for arg, val in given_args.items():
    if arg == 'customizable_properties' and val == []:
        continue
    if val is not None:
        args[arg] = val
```
This isn't a perfect solution however, as it is now impossible to specify that an object should have no customizable properties (empty list) as that gets filtered out. 

## Solution 2: remove `customizable_properties`
Another solution is to just remove the `customizable_properties` feature altogether. It is a never-ending cause of bugs, and confusion for the user. I haven't heard a single user that uses this feature, or is even remotely happy with it.

**Comment by jwaa** [comment]
I would opt for solution 2. At this point this feature is never used, only confuses and is difficult to maintain.

**Comment by thaije** [comment]
Allright, that should be solved with issue https://github.com/matrx-software/matrx/issues/212

**Comment by thaije** [comment]
Closed with https://github.com/matrx-software/matrx/releases/tag/v2.3.0
