### ISSUE TITLE
Update readthedocs logo and colour 

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#45]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thaije](https://github.com/thaije)**
_Thursday Feb 13, 2020 at 12:22 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/44_

----

**Comment by jwaa** [comment]
@thaije Isn't this issue done?

**Comment by thaije** [comment]
The logo has been updated on readthedocs, but the readthedocs colours don't match the current MATRX colour scheme. 
I don't see it really as a problem though and would count this as done if you are also fine with it.
