### ISSUE TITLE
Request if action is possible

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#47]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Friday Feb 14, 2020 at 09:50 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/46_

----

From within an AgentBrain, be able to request the GridWorld if a certain Action with specific arguments is possible to perform.

Should help in preventing duplicate code in checking whether a certain Action will be possible, or for AgentBrains to first decide upon an action just to see if it would succeed.

**Comment by thaije** [comment]
Implemented in the `is_action_possible` [here](https://github.com/matrx-software/matrx/blob/master/matrx/agents/agent_brain.py#L373)
