### ISSUE TITLE
Document MATRX

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#48]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Friday Feb 14, 2020 at 10:10 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/47_

----

Documentation of all MATRX public classes according to the NumpyDocstring guide. 

In addition, documentation of al MATRX private classes for reference to MATRX developers (but which should not be rendered by Sphinx autodoc).

**Comment by jwaa** [comment]
Only partially documented, should put some effort in documenting the rest soon. Though lets split those up into more specific issues. For now, this is closed.
