### ISSUE TITLE
Parameter not used in DropAction

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#60]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Friday Feb 14, 2020 at 14:41 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/59_

----

In ```DropAction._find_drop_loc``` the parameter `agent` is never used.

**Comment by thaije** [comment]
Is used [here](https://github.com/matrx-software/matrx/blob/master/matrx/actions/object_actions.py#L927), issue has already been solved
