### ISSUE TITLE
Responsive website

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#65]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Tuesday Feb 18, 2020 at 19:17 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/64_

----

Currently our website matrx-software.com is not responsive on small screens.

**Comment by thaije** [comment]
Made homepage elements responsive, fixed sticky header, removed border from homepage robot-human hand image.
