### ISSUE TITLE
Objects display over toolbar dropdown

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#70]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thaije](https://github.com/thaije)**
_Thursday Feb 20, 2020 at 14:46 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/69_

----

There was a bug with the visualization depth of objects not being used. This was fixed, but now that objects have a z-index, dropdowns from the toolbar display behind the MATRX objects.

**Comment by thaije** [comment]
Changed the CSS of the header of the visualization, such that MATRX objects no longer display over the God view dropdown.
