### ISSUE TITLE
Update the CIA task to the new version

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#76]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Friday Feb 21, 2020 at 10:34 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/75_

----

From the RVO HAT project, take their task and bring it into the library of standard MATRX task. To do so, we need to make it compatible with the current version.

**Comment by thaije** [comment]
In the project it was chosen to start anew with the latest MATRX version and a new frontend. As such, the old dashboard will not be updated anymore.
