### ISSUE TITLE
Build and distribute our package to PyPi

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#82]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Friday Feb 21, 2020 at 10:39 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/81_

----

We wish our package to be acessable through PyPi, which means we have to upload it there. 

This requires a MATRX account at PyPi, and a first upload to there. 

Note: several issues might depend on this before they can be picked up.

**Comment by mlstolk** [comment]
Done, but have to update it for the first official release.
