### ISSUE TITLE
Create our first setup.py

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#83]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Friday Feb 21, 2020 at 10:40 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/82_

----

To build a python package we need to have a first setup.py.

**Comment by mlstolk** [comment]
Already created by Jasper, but have to update the version number when a new official release is launched and check the licensing details.

**Comment by mlstolk** [comment]
If the licensing details are ok for our first launch (i.e. MIT) this issue can be closed as the change of the version number it is already part of #82 .
@jwaa Can you double check any non-technical definitions in setup.py and close this issue if everything is ok?

**Comment by jwaa** [comment]
IP is slow... will try to contact them again today to check if MIT is fine.
