### ISSUE TITLE
Create a release branch

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#84]
<a href="https://github.com/jwaa"><img src="https://avatars0.githubusercontent.com/u/6059315?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jwaa](https://github.com/jwaa)**
_Friday Feb 21, 2020 at 10:40 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/83_

----

As it is our first release, figure out how release branches and release tags work in GitHub.

**Comment by mlstolk** [comment]
Not much to do now, but when an official release is built:

- update setup.py to match the official version number
- tag the commit with the official version number (see instructions below)
- on Github, go to releases and add the new tag as a new release
- build a wheel and upload it to pypi.org

Adding a tag to a new commit (you have to explicitly push the tag):
git tag -a v1.0.0 -m "First official release"
git push origin --tags

Or adding it to an existing commit by referencing its hash:
git tag -a v1.0.0 -m "First official release" <EXISTING_COMMIT'S_HASH>
