### ISSUE TITLE
Facilitate flat, implicit folder structure with init.py files

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#95]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thaije](https://github.com/thaije)**
_Monday Feb 24, 2020 at 14:21 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/94_

----

B: Flat, but implicit. 
```
From matrxs.agents import AgentBrain 
From matrxs.objects import EnvObject 
From matrxs.tasks.bw4t import BW4TAgent
```

For example: 
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/cross_decomposition/__init__.py

**Comment by matrx-software** [comment]
<a href="https://github.com/mlstolk"><img src="https://avatars0.githubusercontent.com/u/9109477?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mlstolk](https://github.com/mlstolk)**
_Tuesday Feb 25, 2020 at 15:39 GMT_

----

**Encountered a problem.**

Partially working (actions, agents, capabilities, done), but stuck on flattening the **objects** sub-package.

matrx\objects\__init.py__  imports:
```
from .simple_objects import *
from .advanced_objects import *
from .agent_body import *
from .env_object import *

```
When both simple_objects and advanced_objects are included in __init.py__, the latter of the two fails at compile time; apparently because of multiple imports of env_object. 
The order of the first two import lines of __init.py__ determines in which of the files the import of env_object fails.

**Comment by jwaa** [comment]
So if I understand correctly;
Yes, we can flatten the MATRX structure, and this seems to work. However we cannot flatten two modules in the same namespace, when one imports the other. 

In that case I would say we drop the distinction between advanced and simple objects and go for a single module containing both. The reason for this original seperation was that they function as a example/tutorial for objects with varying complexity. This is far less important now.

@thaije @mlstolk My suggestion therefore is to merge the two modules, and adjust the `__init__.py` accordingly.

**Comment by mlstolk** [comment]
Probably that suggestion would work (and is fine for now). I personally cannot implement/test it before the launch. If someone else can finish it, including the suggestion: you can pick it up  
from #94_flat_implicit_folder_structure_test.
