### ISSUE TITLE
Facilitate use of multiple types of messages

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#96]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thaije](https://github.com/thaije)**
_Wednesday Feb 26, 2020 at 13:55 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/95_

----

As of now, there is no "type" parameter for Messages. 
Furthermore, in the _set_messages functions only the mssg.content is saved, so the agent can never identify different types of messages.

**Comment by thaije** [comment]
#230 is planned to be fixed soon, which makes the entire message object available to the agent. In addition, custom message objects that extend the default MATRX message are already supported.
