### ISSUE TITLE
Auto-scroll down to newest chat message

### ISSUE THREAD

**Issue by matrx-software** [matrx-software/matrx#97]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [thaije](https://github.com/thaije)**
_Wednesday Feb 26, 2020 at 14:17 GMT_
_Originally opened as https://github.com/matrxs/MATRXS/issues/96_

----

When the user scrolls up to see previous messages, the chat does not scroll down anymore to new messages.

**Comment by matrx-software** [comment]
<a href="https://github.com/thaije"><img src="https://avatars1.githubusercontent.com/u/2978372?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thaije](https://github.com/thaije)**
_Wednesday Feb 26, 2020 at 15:55 GMT_

----

Fixed in AIMS, see https://ci.tno.nl/gitlab/aims-experimentatie2/matrxs/blob/dev/matrxs_visualizer/static/js/toolbar.js#L413

**Comment by thaije** [comment]
Fixed in https://github.com/matrx-software/matrx/commit/8258725d551bb74d373942fe10ce9fc2dfa0cf24
