### ISSUE TITLE
Build and distribute a Test package to PyPi

### ISSUE THREAD

**Issue by thaije** [matrx-software/matrx#99]
In preperation of #82, first put a test package on PyPi.

**Comment by thaije** [comment]
Is a PyPi package connected to Github, or are versions manual?

**Comment by mlstolk** [comment]
Done, beta version published to pypi.
Have to update it for the first official release

**Comment by mlstolk** [comment]
Have to fix two issues:
- add packages from requirements.txt to setup.py (to autoinstall when installing the wheel)
- matrx_visualizer does not yet have an __init__.py (and is not yet added as a part of the wheel)

**Comment by mlstolk** [comment]
Requirements fixed in setup.py (excluded Sphinx docs).
Remaining issues due to multiple packages (and underlying non-python elements) in matrx_visualizer, as described in #101

**Comment by mlstolk** [comment]
branch #82_build_and_distribute_via_pypi_fixes now includes matrx_visualizer with all its supporting (non .py) files.
